### ISSUE TITLE
Appscript not supported on Windows (and is deprecated)

### ISSUE THREAD

**Issue by lfdversluis** [DidierRLopes/GamestonkTerminal#22]
Running `pip install -r requirements.txt` results in 
```
fatal error C1083:  Cannot open include file: 'Carbon/Carbon.h': No such file or directory
```
on Windows which is required by appscript.

I am not sure if you intend this project to also run on Windows, yet I would like to point out that appscript is no longer maintained, see http://appscript.sourceforge.net/ I am not even sure where you use it searching on GitHub on the strings `App(` and `appscript` yields no hits beyond requirements.txt.

**Comment by lxblvs** [comment]
Same on Ubuntu

**Comment by DidierRLopes** [comment]
Hey @lfdversluis,

You're right. Thank you for pointing this out. This will be removed once I clean the requirements file!

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
